name: NuGet Package Generation 

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:  

  deploy:    
    runs-on: ubuntu-latest
    name: Update or Create NuGet package
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore RKSoftware.Rackspace.ApiClient

      - name: Build
        run: dotnet build RKSoftware.Rackspace.ApiClient --configuration Release --no-restore -warnaserror

      - name: Push to NuGet repository
        run: dotnet nuget push ./RKSoftware.Rackspace.ApiClient/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
